Repository reflex-dev/reflex, pull requests merged in 2023-12, with the labels that each got.

#2262 Implement accordion component
  reflex/.templates/jinja/web/pages/base_page.js.jinja2
  reflex/app.py
  reflex/components/component.py
  reflex/components/radix/primitives/__init__.py
  reflex/components/radix/primitives/accordion.py
  reflex/components/radix/primitives/accordion.pyi
  reflex/components/radix/themes/typography.py
  reflex/vars.py
Labels: ready-for-review

#2266 [REF-1417] Convert underscore-prefixed style props to pseudo selector
  integration/test_input.py
  integration/test_var_operations.py
  reflex/components/component.py
  reflex/style.py
  reflex/utils/format.py
  tests/test_style.py
  tests/utils/test_format.py
Labels: ready-for-review

#2284 [REF-1464] Handle requirements.txt encoding
  poetry.lock
  pyproject.toml
  reflex/constants/config.py
  reflex/utils/prerequisites.py
  tests/test_prerequisites.py
Labels: linear

#2311 add size prop to the number input
  reflex/components/forms/numberinput.py
  reflex/components/forms/numberinput.pyi
Labels: waiting for submitter
